### ISSUE TITLE
Method for converting resource.Payment object to json 

### ISSUE THREAD

**Issue by BenCoDev** [payplug/payplug-python#1]
I can't find any method making it easy to convert resource.Payment object to json.  
Is it possible to add one ?
That would be useful since payplug.Payment.create returns a resource.Payment object.

**Comment by splanquart** [comment]
What is the use case of this issue?

**Comment by BenCoDev** [comment]
I wanted to access nested attributes of the resource.

However, I found my way with dot notation.

Sorry for the inconvenience,
